version: '3'

services:
  backendcomments:
    build:
      dockerfile: Dockerfile
      context: "./comments"
    volumes:
      - /app/node_modules
      - ./comments:/app
    ports:
      - 4001:4001
  backendposts:
    build:
      dockerfile: Dockerfile
      context: "./posts"
    volumes:
      - /app/node_modules
      - ./posts:/app
    ports:
      - 4000:4000
  backendquery:
    build:
      dockerfile: Dockerfile
      context: "./query"
    volumes:
      - /app/node_modules
      - ./query:/app
    ports:
      - 4002:4002
  backendevent-bus:
    build:
      dockerfile: Dockerfile
      context: "./event-bus"
    volumes:
      - /app/node_modules
      - ./event-bus:/app
    ports:
      - 4005:4005

  frontend:
    build:
      dockerfile: Dockerfile
      context: "./client"
    ports:
      - 3000:3000 
    volumes:
      - /app/node_modules
      - ./Client:/app
    depends_on:
      - backendcomments
      - backendposts
      - backendquery
      - backendevent-bus